### PR TITLE
URGENT | Adding missing fields and imports

### PR DESCRIPTION
**Pull request by Mo7amm1d**
I just checked on my last PR and found some missing imports and fields. This is an URGENT request and fixes to make the middleware functional again.

Sorry for the inconvenience.

### CODE REVIEW

**Comment by tlaceby** [comment]
Yea since this library is still so small and not used by anyone but you right now I didn't even not even bother testing it. 

No problem glad you were able to get it to how you like.

**Comment by tlaceby** [comment]
I think I might add 3 external methods that accept a request object and then return the data. Just in case people don't want to use the middleware functionality.

**Comment by Mo7amm1d** [comment]
> Yea since this library is still so small and not used by anyone but you right now I didn't even not even bother testing it.
> 
> No problem glad you were able to get it to how you like.

I actually was thinking of making the same library, cause when I searched for multipart for opine, I didn't find any. But after some days of researching and seeing other libraries and trying to figure out how to get to multipart data, I decided to make it.. then I said let's search again for the library and I stumbled on your library. You saved me a lot of hustle and time, and for that, I think you so much and I appreciate your effort.

I hope we can extend the library with more features in the future.

**Comment by Mo7amm1d** [comment]
> I think I might add 3 external methods that accept a request object and then return the data. Just in case people don't want to use the middleware functionality.

Like parsing methods? that would be great! Looking forward to seeing it.

**Comment by tlaceby** [comment]
Yea I personally think this library would be slightly better if it wasn't middleware at all. Instead having a function that takes a OpineRequest and returns the multipart data. That way I don't have to worry about all the typescript types I run into.

**Pull request merged**
